DROP TABLE IF EXISTS educational_sources;
DROP TABLE IF EXISTS emergency_services;
DROP TABLE IF EXISTS users;

CREATE EXTENSION IF NOT EXISTS h3 CASCADE;
CREATE EXTENSION IF NOT EXISTS h3_postgis CASCADE;

CREATE TABLE users (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    h3 BIGINT NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE emergency_services (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL,
    h3 BIGINT NOT NULL
);

CREATE TABLE educational_sources (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    url VARCHAR(500) NOT NULL,
    description TEXT NOT NULL,
    target_crime_type VARCHAR(50) NOT NULL,
    h3 BIGINT NOT NULL,
    added_at TIMESTAMP NOT NULL DEFAULT now()
);
